# The purpose of this `meta.yml` file is to allow you to add relevant pieces of metadata
# to your package before it is uploaded to the Expectation Gallery.
#
# While most of the information about the data is parsed through the `great_expectations_contrib`
# CLI, this file allows you to configure particular settings like images and individuals.
#
# The three primary sections of the file are:
#   1. general:        High-level, miscellaneous details about the package
#   2. code_owners:    The individuals responsible for the package
#   3. domain_experts: Any individual with highly specialized knowledge of the given domain

general:
  package_name: {{ cookiecutter.package_name }}
  icon: ~ # May be a relative path to `assets/` or a URL
  description: {{ cookiecutter.package_description }}

# Please add more code owners as you see fit
code_owners:
  - username: {{ cookiecutter.full_name }}
    full_name: {{ cookiecutter.github_username }}

# Please fill in the details and add more domain experts as you see fit
domain_experts:
  - full_name: ~
    social_links:
      - account_type: ~ # May be one of TWITTER | INSTAGRAM | LINKEDIN | MEDIUM
        identifier: ~
    picture: ~ # May be a relative path to `assets/` or a URL
